### ISSUE TITLE
Parsing invalid length .exe results in raw ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Frotty** [dorkbox/PeParser#3]
Hi, if you don't mind, you could add a check to prevent this exception from happening:
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 61
	at dorkbox.util.bytes.LittleEndian$UShort_.from(LittleEndian.java:276)
	at dorkbox.peParser.ByteArray.readUShort(ByteArray.java:53)
	at dorkbox.peParser.PE.getPEOffset(PE.java:201)
	at dorkbox.peParser.PE.isPE(PE.java:208)
	at dorkbox.peParser.PE.fromInputStream(PE.java:102)
	at dorkbox.peParser.PE.<init>(PE.java:70)
	at dorkbox.peParser.PE.getVersion(PE.java:260)
```
if the input file is of invalid length, since it isn't caught/thrown. Perhaps throw your own exception.

**Comment by dorkbox** [comment]
(super easy to add this, btw...)
