### ISSUE TITLE
ResourceType lookup invalid ordinal NPE

### ISSUE THREAD

**Issue by WaterKnight** [dorkbox/PeParser#4]
```
Caused by: java.lang.NullPointerException
	at dorkbox.peParser.types.ResourceDirName.<init>(ResourceDirName.java:87)
	at dorkbox.peParser.headers.resources.ResourceDirectoryEntry.<init>(ResourceDirectoryEntry.java:71)
	at dorkbox.peParser.headers.resources.ResourceDirectoryHeader.<init>(ResourceDirectoryHeader.java:62)
	at dorkbox.peParser.PE.fromInputStream(PE.java:135)
	at dorkbox.peParser.PE.<init>(PE.java:68)
```

Tested in 2.13 and 2.9 releases. The index in my case is 256. The executable in question is not mine but from a famous computer game (Warcraft III), so should be valid.

**Comment by Frotty** [comment]
@dorkbox still an issue. any feedback on this?

**Comment by dorkbox** [comment]
Sorry, I didn’t see this issue! I’ll look into this.

**Comment by Frotty** [comment]
@dorkbox I think the new version already addresses some of this, at least it doesn't produce the same error anymore. Any insights from your side?

**Comment by Frotty** [comment]
@dorkbox Did you check this out any further?

**Comment by dorkbox** [comment]
It’s resolved.
