### ISSUE TITLE
Error parsing PE file

### ISSUE THREAD

**Issue by bonigarcia** [dorkbox/PeParser#6]
I want to pare the resources from the `.rsrc` section of the following [PE file](https://drive.google.com/file/d/1w2MxLRJt8KjJ9NlR0NfuTjf6wlHvxSQm/view?usp=sharing) (147.7 MB). I got that file from the [Edge MSI installer](https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/0a8155d6-0937-4937-8712-1930f09598eb/MicrosoftEdgeEnterpriseX64.msi) (inside the Binary.MicrosoftEdgeInstaller stream).

I tried to use PeParser from Java as follows:

```
PE pe = new PE("/path/to/MicrosoftEdge_X64_116.0.1938.76.exe");
```

... but I got the following error:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 685592958
	at dorkbox.bytes.LittleEndian$UInt_.from-_W1zjd8(LittleEndian.kt:259)
	at dorkbox.peParser.ByteArray.readUInt-OGnWXxg(ByteArray.kt:36)
	at dorkbox.peParser.headers.resources.ResourceDataEntry.<init>(ResourceDataEntry.kt:33)
	at dorkbox.peParser.headers.resources.ResourceDirectoryEntry.<init>(ResourceDirectoryEntry.kt:85)
	at dorkbox.peParser.headers.resources.ResourceDirectoryHeader.<init>(ResourceDirectoryHeader.kt:57)
	at dorkbox.peParser.PE.fromInputStream(PE.kt:192)
	at dorkbox.peParser.PE.<init>(PE.kt:119)
```

Any idea of what is wrong here? Thanks in advance.

**Comment by dorkbox** [comment]
Sorry, I didn’t see this issue! I’ll look into this! Thank you for providing an example
