### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DameerGamlet** [dorkbox/PeParser#7]
Exception in thread "main" java.lang.NumberFormatException: Value is out of range : 5368709120
	at dorkbox.util.bytes.UInteger.rangeCheck(UInteger.java:260)
	at dorkbox.util.bytes.UInteger.valueOf(UInteger.java:219)
	at dorkbox.peParser.types.ImageBase_Wide.format(ImageBase_Wide.java:39)
	at dorkbox.peParser.PE.getInfo(PE.java:175)
	at TaskThree.main(TaskThree.java:47)

Execution failed for task ':task-3:TaskThree.main()'.
> Process 'command '/usr/lib/jvm/java-17-openjdk/bin/java'' finished with non-zero exit value 1

for:
`pe.getInfo()`

**Comment by eix128** [comment]
This library is for windows , not for linux afaik ?

**Comment by dorkbox** [comment]
This is cross platform — can you provide a link to the EXE?

**Comment by eix128** [comment]
yeah , its cross platform i know but , does it support linux elf binaries ?

**Comment by DameerGamlet** [comment]
Updated to the latest version, problem solved
